# Generated by Django 3.0.4 on 2020-03-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router', models.CharField(max_length=255, unique=True)),
                ('mac', models.CharField(max_length=17, unique=True)),
            ],
        ),
    ]
