# Generated by Django 3.0.4 on 2020-03-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MACSniff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MACSniff.Router')),
            ],
        ),
    ]
