# Generated by Django 3.0.4 on 2020-03-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MACSniff', '0002_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('mac', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MACSniff.ClassRoom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MACSniff.Student')),
            ],
        ),
    ]
